CI: confirm webseed redirects + versioned hashes

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -67,6 +67,28 @@ jobs:
           VERSION: $VERSION
           VERSION_GUI: $VERSION_GUI
 
+      - name: check getmonero webseed + versioned hashes file
+        run: |
+          CDN_URL="https://downloads.getmonero.org"
+          if ! wget --spider -q "$CDN_URL/hashes-$VERSION.txt"; then
+            echo "::warning title=Torrent-Webseed-URLs::FAILED: $CDN_URL/hashes-$VERSION.txt"
+          fi
+          if ! wget --spider -q "$CDN_URL/hashes-$VERSION_GUI.txt"; then
+            echo "::warning title=Torrent-Webseed-URLs::FAILED: $CDN_URL/hashes-$VERSION_GUI.txt"
+          fi
+          for file in $(awk '/monero-/ {print $2}' "hashes.txt"); do
+            dir=cli
+            part="monero-$VERSION"
+            if [[ $file =~ gui ]]; then
+                dir=gui
+                part="monero-gui-$VERSION_GUI"
+            fi
+            url=$CDN_URL/${part}/${dir}/${file}
+            if ! wget --spider -q "$url"; then
+              echo "::warning title=Torrent-Webseed-URLs::FAILED: $url"
+            fi
+          done
+
       # note: its possible gui + cli have different versions. combine them for the key.
       - uses: actions/cache@v4
         id: binaries_cache
